//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace charlieahill_Gallery_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("charlieahill_Gallery_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon chg {
            get {
                object obj = ResourceManager.GetObject("chg", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;***&quot;&gt;
        ///		&lt;div id=&quot;galleryLink&quot;&gt;
        ///			&lt;div id=&quot;image&quot;&gt;&lt;img src=&quot;***&quot;&gt;&lt;/div&gt;
        ///			&lt;div id=&quot;text&quot;&gt;***&lt;/div&gt;
        ///		&lt;/div&gt;
        ///	&lt;/a&gt;.
        /// </summary>
        internal static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --README-- This file contains the text that should be copied into the previously existing gallery file, to incorporate this gallery tab into the list of previous galleries.
        /// </summary>
        internal static string galleryBlurb {
            get {
                return ResourceManager.GetString("galleryBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;***&quot;&gt;
        ///		&lt;div id=&quot;contentLink&quot;&gt;
        ///			&lt;div id=&quot;text&quot;&gt;***&lt;/div&gt;
        ///			&lt;div id=&quot;date&quot;&gt;***&lt;/div&gt;***
        ///			&lt;div id=&quot;image&quot;&gt;&lt;img src=&quot;***/***&quot;&gt;&lt;/div&gt;***
        ///		&lt;/div&gt;
        ///	&lt;/a&gt;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --README-- This file contains the text that should be copied into the previously existing index file, to incorporate this gallery tab into the list of previous galleries.
        /// </summary>
        internal static string indexBlurb {
            get {
                return ResourceManager.GetString("indexBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;charliehill - ***&lt;/title&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;adhill.css&quot;&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;Charlie Hill blog - ***&quot;&gt;
        ///&lt;meta name=&quot;keywords&quot; content=&quot;Charlie Hill, ***&quot;&gt;
        ///&lt;?php include(&apos;head.txt&apos;) ?&gt;
        ///&lt;meta property=&quot;og:site_name&quot; content=&quot;Charlie Hill blog&quot; /&gt;
        ///&lt;meta property=&quot;og:url&quot; content=&quot;http://wwww.charlieahill.co.uk/***&quot; /&gt;
        ///&lt;meta property=&quot;og:title&quot; content=&quot;Charlie Hill blog - ***&quot; /&gt;
        ///&lt;meta property=&quot;og:description&quot; content=&quot;Cha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string php {
            get {
                return ResourceManager.GetString("php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sw {
            get {
                object obj = ResourceManager.GetObject("sw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;gal.css&quot;&gt;
        ///&lt;div id=&quot;splitter&quot;&gt;***&lt;/div&gt;
        ///&lt;div id=&quot;text&quot;&gt;***
        ///&lt;br&gt;&lt;br&gt;Click on thumbnails to enlarge.&lt;/div&gt;
        ///&lt;div id=&quot;frame&quot;&gt;
        ///&lt;div id=&quot;galleryLink&quot;&gt;
        ///&lt;div id=&quot;facebook&quot;&gt;
        ///&lt;div class=&quot;fb-like&quot; data-href=&quot;http://www.charlieahill.co.uk/***&quot; data-layout=&quot;standard&quot; data-action=&quot;like&quot; data-show-faces=&quot;true&quot; data-share=&quot;true&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;fb-comments&quot; data-href=&quot;http://www.charlieahill.co.uk/***&quot; data-width=&quot;420&quot; data-numposts=&quot;5&quot; data-colorscheme=&quot;light&quot;&gt;&lt;/div&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;gal.css&quot;&gt;
        ///&lt;div id=&quot;splitter&quot;&gt;***&lt;/div&gt;
        ///&lt;div id=&quot;text&quot;&gt;***
        ///&lt;br&gt;&lt;br&gt;Click on thumbnails to enlarge.&lt;/div&gt;
        ///&lt;div id=&quot;frame&quot;&gt;
        ///&lt;div id=&quot;galleryLink&quot;&gt;
        ///&lt;div id=&quot;facebook&quot;&gt;
        ///&lt;div class=&quot;fb-like&quot; data-href=&quot;http://www.charlieahill.co.uk/ag/***&quot; data-layout=&quot;standard&quot; data-action=&quot;like&quot; data-show-faces=&quot;true&quot; data-share=&quot;true&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;fb-comments&quot; data-href=&quot;http://www.charlieahill.co.uk/ag/***&quot; data-width=&quot;420&quot; data-numposts=&quot;5&quot; data-colorscheme=&quot;light&quot;&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string txtag {
            get {
                return ResourceManager.GetString("txtag", resourceCulture);
            }
        }
    }
}
